### ISSUE TITLE
Prepare Cohort Call 1 [ 2024-noaa]

### ISSUE THREAD

**Issue by stefaniebutland** [nmfs-openscapes/cohort-planning#7]
This is the same for every Cohort Call except the last. Create one issue for every Cohort Call and add the Call number to the issue title.

- [x] create Agenda (kyber); make manual edits
  - [x] 2024-noaa-a
  - [x] 2024-noaa-b
  - [x]  2024-noaa-c
- [x] review roles and timing

**Comment by stefaniebutland** [comment]
Consider how to include some of @AHolder1 's approaches to normalizing cohort call behaviours like raise hands, call on person, unmute to respond, popcorn to next person with raised hand. 

Anna shared the Call 1 agenda w Stef by email (private since has participant names)

- Takes the time to talk about positionality, power  etc and how it can affect how we learn. Flatten the hierarchy. “Leave shame at the door”. “This space is different …” from what you are likely used to at [ workplace ]
- Not even screensharing the agenda at start!
- All videos are on! 
- Reading out some roll call items “something you’re good at” is good in Call 1

- This is so amazing: Anna gets everyone to raise their Teams hand, then calls on someone to read a bullet out loud (from the POP?) “strengthen teamwork…”, then they lower their Teams / Zoom / Meet hand and call on another person with raised hand
- Let’s use this to normalize unmute etc
- First activity before any lesson is breakout room with intro, one workflow thing that’s great, one thing you want to improve on.
  - back in Main, First person to speak chooses someone from raised hands to go next. Unmute, speak up. Everyone spoke! wut!
Practicing facilitation.

**Comment by AHolder1** [comment]
Re: not sharing the agenda at the start - we introduce this and practice it during the 1:1s the week before the call. So folks have already been "braced" to normalize cameras on and navigating docs/slides on their own. 

Re: raised hands - I was also thinking about having everyone raise hands sooner and have some folks read COC bullets...buuuut I forgot. ha! Adding that in, especially if you have a full cohort, enables everyone to participate in the process. Because I didn't do the COC bit at the top, a couple of folks had hands raised but we didn't have enough bullets for all.

**Comment by stefaniebutland** [comment]
Review Google Meet setup. Breakout rooms are more restrictive than Zoom as I recall.

[Use breakout rooms in Google Meet](https://support.google.com/meet/answer/13054147?hl=en&authuser=1&ref_topic=14074639&sjid=105705301600925752-NC&co=GOOGLE_MEET._MeetingUserType%3DHost&oco=0)

**Comment by stefaniebutland** [comment]
- [x] Invite @IleanaF to share her Better Science story and introduce the Pathways to Open Science program
- [x] invite MML team to share their Better Science story 
  - great existing content in [A Year of Open Science Community Building at NOAA Fisheries](https://www.youtube.com/watch?v=n1VaV8f6qQE&list=PLChfyH8TVDGnB_zDCm8d9oonMomfk8v9X&index=14) presentation for YOS Culminating Conference March 2024. [Slides 13-16](https://docs.google.com/presentation/d/1xR0UyplIJbTJQmog8tx2OKNi6jeK7LvegJq5vai5Y2k/edit#slide=id.g2c4f45e8206_0_0) presented by Josh London for Brian Fadely
  - also great content presented to Openscapes Champions as part of Data Strategies lesson in Winter 2022. Shared the story of impact on their reporting and team culture (13-min [recording](https://youtu.be/whC4FyHuVg8) | [slides](https://docs.google.com/presentation/d/16oScbiL9cXvcUZCpsquc39csq0SbP6vSX3CJ6L4wc7w/) with detailed speaker notes). Rod Towell, Nancy Young, Tony Orr, Erin Richmond, and Brian Fadely

**Comment by stefaniebutland** [comment]
MML confirmed by Brian Fadely. Once Ileana confirms, decide how much time for each to present

**Comment by jules32** [comment]
@stefaniebutland I've reviewed the Draft 01 agenda and it looks good to go! I think your idea of copying this across to different Google Docs rather than making NMFS-specific edits to Kyber is a good one. Thank you!
